---
# Leaf-02 variables

router_id: 10.2.0.2

loopbacks:
  - interface: Loopback0
    addr: 10.2.0.2
    mask: 32
    description: "Routing loopback interface"

  - interface: Loopback1
    addr: 10.3.0.2
    mask: 32
    description: "VTEP loopback interface"

spine_uplinks:
  - interface: Ethernet1/1
    addr: 10.4.0.5
    mask: 30
    description: "Connected to Spine-01 Ethernet1/2"
 
access_ports:
  - interface: Ethernet1/3
    description: "Connected to PC-01"
    access_vlan: 2300