---
# Spine-01 variables

router_id: 10.2.0.3

loopbacks:
  - interface: Loopback0
    addr: 10.2.0.3
    mask: 32
    description: "Routing loopback interface"

  - interface: Loopback254
    addr: 10.254.254.1
    mask: 32
    description: "RP loopback interface"

leaf_downlinks:
  - interface: Ethernet1/1
    addr: 10.4.0.2
    mask: 30
    description: "Connected to Leaf-01 Ethernet1/1"

  - interface: Ethernet1/2
    addr: 10.4.0.6
    mask: 30
    description: "Connected to Leaf-02 Ethernet1/1"